export const GLOSSARY_TERMS = [
  "additional-medicare-tax",
  "adjusted-gross-income",
  "adjustment",
  "alternative-minimum-tax",
  "backup-withholding",
  "capital-gain",
  "collectibles",
  "credit",
  "deduction",
  "dividend",
  "federal-income-tax",
  "golden-parachute",
  "gross-income",
  "income",
  "income-tax",
  "loss-carryover",
  "modified-adjusted-gross-income",
  "net-investment-income-tax",
  "ordinary-dividends",
  "qualified-business-income",
  "qualified-dividends",
  "qualified-opportunity-fund",
  "qualified-small-business-stock",
  "recapture",
  "section-1202",
  "section-1250",
  "section-1411",
  "section-199A",
  "section-897",
  "security",
  "specified-private-activity-bond",
  "tax-due",
  "tax-liability",
  "tax-refund",
  "taxable-income",
  "wages",
  "wash-sale",
  "withholding",
] as const;

export type GlossaryTerm = (typeof GLOSSARY_TERMS)[number];
